---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: "vps"
    prompt: "VPS"
    private: no
  tasks:
    - add_host:
        name: "{{ vps }}"
        groups: dynamically_created_hosts


- hosts: dynamically_created_hosts

  vars_prompt:
    - name: "domain"
      prompt: "Domain name"
      private: no

    - name: "user"
      prompt: "System user"
      private: no

    - name: "password"
      prompt: "System password"
      encrypt: "sha512_crypt"
      private: yes

    - name: "mysql_user"
      prompt: "MySQL user"
      private: no

    - name: "mysql_db"
      prompt: "MySQL DB"
      private: no

    - name: "mysql_password"
      prompt: "MySQL password"
      private: yes

    - name: "mysql_root_password"
      prompt: "MySQL root password"
      private: yes

    - name: "install_mysql"
      prompt: "Would you like to configure MySQL server"
      default: 'n'
      private: no

    - name: "install_apache_php"
      prompt: "Would you like to configure Apache & php"
      default: 'n'
      private: no

    - name: "install_nginx_php"
      prompt: "Would you like to configure nginx & php-fpm"
      default: 'n'
      private: no

    - name: "php_fpm_pool_name"
      prompt: "php-fpm pool name"
      private: no

    - name: "php_fpm_pool_listen"
      prompt: "php-fpm pool listen"
      default: 8001
      private: no

    - name: "install_composer"
      prompt: "Would you like to install composer"
      default: 'n'
      private: no

    - name: "install_grunt"
      prompt: "Would you like to install sass, less & grunt"
      default: 'n'
      private: no

  pre_tasks:
    - include: "system.yml"

    - include: "user.yml"
      when: user and password

  roles:
    - { role: ezyatev.apache-php, when: install_apache_php == 'y' and domain and user and password }
    - { role: nbz4live.php-fpm, when: install_nginx_php == 'y' and domain and user and password }
    - { role: jdauphant.nginx, when: install_nginx_php == 'y' and domain and user and password }
    - { role: geerlingguy.composer, when: install_composer == 'y' and user and password }
    - { role: geerlingguy.mysql, when: install_mysql == 'y' and mysql_user and mysql_db and mysql_password }
    - { role: gotansible.nodejs, when: install_grunt == 'y' and user and password }
    - { role: AsianChris.rubygems, when: install_grunt == 'y' and user and password }
    - { role: manala.npm, when: install_grunt == 'y' and user and password }

  tasks:

    - include: "webserver.yml"
      when: domain and user and password

    - include: "grunt.yml"
      when: install_grunt == 'y' and user and password