---

- name: dependencies
  include_tasks: depend.yml

- name: debian install
  include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: configure
  include_tasks: config.yml


